
export const tableHeaders=[
    {
        id :0,
        name:"checkbox",
        displayName:"",

    },
    {
        id :1,
        name:"taskname",
        displayName:"Task Name",

    },
    {
        id :2,
        name:"description",
        displayName:"Description",
        
    },
    {
        id :3,
        name:"assigne",
        displayName:"Assigne",
        
    },
    {
        id :4,
        name:"startdate",
        displayName:"Start Date",
        
    },
    {
        id :5,
        name:"enddate",
        displayName:"End Date",
        
    },
    {
        id :6,
        name:"Status",
        displayName:"Status",
        
    }
]




export const tableRowsData = [
    {
        id: 1,
        name: "taskname1",
        displayName: "Task Name 1",
        description: "Initial project setup and repository creation",
        assigne: "Gopinadh Vallabhneni",
        status: "New",
        startdate: "2024-01-01",
        enddate: "2024-02-02",
    },
    {
        id: 2,
        name: "taskname2",
        displayName: "Task Name 2",
        description: "Create user authentication module",
        assigne: "Amit Kumar",
        status: "In Progress",
        startdate: "2024-01-05",
        enddate: "2024-02-10",
    },
    {
        id: 3,
        name: "taskname3",
        displayName: "Task Name 3",
        description: "Implement project dashboard UI",
        assigne: "Sara Lee",
        status: "Completed",
        startdate: "2024-01-10",
        enddate: "2024-01-25",
    },
    {
        id: 4,
        name: "taskname4",
        displayName: "Task Name 4",
        description: "Setup CI/CD pipelines",
        assigne: "John Doe",
        status: "New",
        startdate: "2024-01-15",
        enddate: "2024-03-01",
    },
    {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    },
    {
        id: 6,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    },
    {
        id: 7,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    },
    {
        id: 8,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    },
    {
        id: 9,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    },
    {
        id: 10,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    },
    {
        id: 11,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    },
    {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    },
    {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    },
    {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    }, {
        id: 5,
        name: "taskname5",
        displayName: "Task Name 5",
        description: "Write end-to-end tests",
        assigne: "Emily Zhang",
        status: "In Progress",
        startdate: "2024-02-01",
        enddate: "2024-02-28",
    },
];
