const usersData = {
    columnsData :[ {
        fieldname  : "select",
        displayName : "",
        sort : false,
        search : false,
        tooltip : false,
        customCell : false,
        order : 0,
        type : "checkbox",
        width : 0,
        minWidth : 0,
        resizable : false,
        editable : false,
        filterable : false,
        showCheckbox : false,
    },{
        fieldname : "username",
        displayName : "Username",
        sort : true,
        search : true,
        tooltip : true,
        customCell : false,
        order : 1,
        type : "string",
        width : 150,
        minWidth : 150,
        resizable : true,
        editable : false,
        filterable : true,
    },{
        fieldname : "email",
        displayName : "Email",
        sort : true,
        search : true,
        tooltip : true,
        customCell : false,
        order : 2,
        type : "string",
        width : 150,
        minWidth : 150,
        resizable : true,
        editable : false,
        filterable : true,
    },{
        fieldname : "phone",
        displayName : "Phone",
        sort : true,
        search : true,
        tooltip : true,
        customCell : true,
        order : 3,
        type : "string",
        width : 150,
        minWidth : 150,
        resizable : true,
        editable : true,
        filterable : true,
    },{
        fieldname : "address",
        displayName : "Address",
        sort : true,
        search : true,
        tooltip : true,
        customCell : true,
        order : 4,
        type : "string",
        width : 150,
        minWidth : 150,
        resizable : true,
        editable : true,
        filterable : true,
    },{
        fieldname : "city",
        displayName : "City",
        sort : true,
        search : true,
        tooltip : true,
        customCell : true,
        order : 5,
        type : "string",
        width : 150,
        minWidth : 150,
        resizable : true,
        editable : true,
        filterable : true,
    },
    { fieldname : "role",
        displayName : "Role",
        sort : true,
        search : true,
        tooltip : true,
        customCell : true,
        order : 6,
        type : "string",
        width : 150,
        minWidth : 150,
        resizable : true,
        editable : true,
        filterable : true,
    },
    {
        fieldname : "createdat",
        displayName : "Created At",
        sort : true,
        search : true,
        tooltip : true,
        customCell : true,
        order : 7,
        type : "string",
        width : 150,
        minWidth : 150,
        resizable : true,
        editable : true,
        filterable : true,
    },
    {
        fieldname : "updatedat",
        displayName : "Updated At",
        sort : true,
        search : true,
        tooltip : true,
        customCell : true,
        order : 8,
        type : "string",
        width : 150,
        minWidth : 150,
        resizable : true,
        editable : true,
        filterable : true,
    }
],
    rowsData :[ 
        { username: { value: "John Doe", type: "string" }, email: { value: "john.doe@company.com", type: "string" }, phone: { value: "+1-555-0101", type: "string" }, address: { value: "123 Main St", type: "string" }, city: { value: "New York", type: "string" }, role: { value: "Admin", type: "string" }, createdat: { value: "2024-01-15", type: "string" }, updatedat: { value: "2024-10-01", type: "string" } },
        { username: { value: "Jane Smith", type: "string" }, email: { value: "jane.smith@company.com", type: "string" }, phone: { value: "+1-555-0102", type: "string" }, address: { value: "456 Oak Ave", type: "string" }, city: { value: "Los Angeles", type: "string" }, role: { value: "Manager", type: "string" }, createdat: { value: "2024-01-20", type: "string" }, updatedat: { value: "2024-09-28", type: "string" } },
        { username: { value: "Mike Johnson", type: "string" }, email: { value: "mike.j@company.com", type: "string" }, phone: { value: "+1-555-0103", type: "string" }, address: { value: "789 Pine Rd", type: "string" }, city: { value: "Chicago", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-02-01", type: "string" }, updatedat: { value: "2024-09-30", type: "string" } },
        { username: { value: "Sarah Williams", type: "string" }, email: { value: "s.williams@company.com", type: "string" }, phone: { value: "+1-555-0104", type: "string" }, address: { value: "321 Elm St", type: "string" }, city: { value: "Houston", type: "string" }, role: { value: "Designer", type: "string" }, createdat: { value: "2024-02-10", type: "string" }, updatedat: { value: "2024-10-02", type: "string" } },
        { username: { value: "Robert Brown", type: "string" }, email: { value: "r.brown@company.com", type: "string" }, phone: { value: "+1-555-0105", type: "string" }, address: { value: "654 Maple Dr", type: "string" }, city: { value: "Phoenix", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-02-15", type: "string" }, updatedat: { value: "2024-09-25", type: "string" } },
        { username: { value: "Emily Davis", type: "string" }, email: { value: "emily.d@company.com", type: "string" }, phone: { value: "+1-555-0106", type: "string" }, address: { value: "987 Cedar Ln", type: "string" }, city: { value: "Philadelphia", type: "string" }, role: { value: "Analyst", type: "string" }, createdat: { value: "2024-03-01", type: "string" }, updatedat: { value: "2024-10-03", type: "string" } },
        { username: { value: "David Miller", type: "string" }, email: { value: "d.miller@company.com", type: "string" }, phone: { value: "+1-555-0107", type: "string" }, address: { value: "147 Birch St", type: "string" }, city: { value: "San Antonio", type: "string" }, role: { value: "Manager", type: "string" }, createdat: { value: "2024-03-05", type: "string" }, updatedat: { value: "2024-09-29", type: "string" } },
        { username: { value: "Lisa Anderson", type: "string" }, email: { value: "lisa.a@company.com", type: "string" }, phone: { value: "+1-555-0108", type: "string" }, address: { value: "258 Spruce Ave", type: "string" }, city: { value: "San Diego", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-03-10", type: "string" }, updatedat: { value: "2024-10-01", type: "string" } },
        { username: { value: "James Wilson", type: "string" }, email: { value: "j.wilson@company.com", type: "string" }, phone: { value: "+1-555-0109", type: "string" }, address: { value: "369 Willow Way", type: "string" }, city: { value: "Dallas", type: "string" }, role: { value: "Designer", type: "string" }, createdat: { value: "2024-03-15", type: "string" }, updatedat: { value: "2024-09-27", type: "string" } },
        { username: { value: "Mary Martinez", type: "string" }, email: { value: "mary.m@company.com", type: "string" }, phone: { value: "+1-555-0110", type: "string" }, address: { value: "741 Ash Blvd", type: "string" }, city: { value: "San Jose", type: "string" }, role: { value: "Admin", type: "string" }, createdat: { value: "2024-03-20", type: "string" }, updatedat: { value: "2024-10-04", type: "string" } },
        { username: { value: "Thomas Garcia", type: "string" }, email: { value: "t.garcia@company.com", type: "string" }, phone: { value: "+1-555-0111", type: "string" }, address: { value: "852 Hickory Rd", type: "string" }, city: { value: "Austin", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-04-01", type: "string" }, updatedat: { value: "2024-09-26", type: "string" } },
        { username: { value: "Patricia Lopez", type: "string" }, email: { value: "p.lopez@company.com", type: "string" }, phone: { value: "+1-555-0112", type: "string" }, address: { value: "963 Poplar St", type: "string" }, city: { value: "Jacksonville", type: "string" }, role: { value: "Analyst", type: "string" }, createdat: { value: "2024-04-05", type: "string" }, updatedat: { value: "2024-10-02", type: "string" } },
        { username: { value: "Daniel Taylor", type: "string" }, email: { value: "d.taylor@company.com", type: "string" }, phone: { value: "+1-555-0113", type: "string" }, address: { value: "159 Walnut Dr", type: "string" }, city: { value: "Fort Worth", type: "string" }, role: { value: "Manager", type: "string" }, createdat: { value: "2024-04-10", type: "string" }, updatedat: { value: "2024-09-30", type: "string" } },
        { username: { value: "Linda Hernandez", type: "string" }, email: { value: "l.hernandez@company.com", type: "string" }, phone: { value: "+1-555-0114", type: "string" }, address: { value: "357 Beech Ln", type: "string" }, city: { value: "Columbus", type: "string" }, role: { value: "Designer", type: "string" }, createdat: { value: "2024-04-15", type: "string" }, updatedat: { value: "2024-10-03", type: "string" } },
        { username: { value: "Christopher Lee", type: "string" }, email: { value: "c.lee@company.com", type: "string" }, phone: { value: "+1-555-0115", type: "string" }, address: { value: "468 Cherry Ave", type: "string" }, city: { value: "Charlotte", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-04-20", type: "string" }, updatedat: { value: "2024-09-28", type: "string" } },
        { username: { value: "Barbara White", type: "string" }, email: { value: "b.white@company.com", type: "string" }, phone: { value: "+1-555-0116", type: "string" }, address: { value: "579 Magnolia Rd", type: "string" }, city: { value: "San Francisco", type: "string" }, role: { value: "Admin", type: "string" }, createdat: { value: "2024-05-01", type: "string" }, updatedat: { value: "2024-10-01", type: "string" } },
        { username: { value: "Matthew Harris", type: "string" }, email: { value: "m.harris@company.com", type: "string" }, phone: { value: "+1-555-0117", type: "string" }, address: { value: "680 Dogwood St", type: "string" }, city: { value: "Indianapolis", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-05-05", type: "string" }, updatedat: { value: "2024-09-29", type: "string" } },
        { username: { value: "Elizabeth Clark", type: "string" }, email: { value: "e.clark@company.com", type: "string" }, phone: { value: "+1-555-0118", type: "string" }, address: { value: "791 Sycamore Dr", type: "string" }, city: { value: "Seattle", type: "string" }, role: { value: "Analyst", type: "string" }, createdat: { value: "2024-05-10", type: "string" }, updatedat: { value: "2024-10-04", type: "string" } },
        { username: { value: "Joseph Lewis", type: "string" }, email: { value: "j.lewis@company.com", type: "string" }, phone: { value: "+1-555-0119", type: "string" }, address: { value: "802 Redwood Ln", type: "string" }, city: { value: "Denver", type: "string" }, role: { value: "Manager", type: "string" }, createdat: { value: "2024-05-15", type: "string" }, updatedat: { value: "2024-09-27", type: "string" } },
        { username: { value: "Nancy Robinson", type: "string" }, email: { value: "n.robinson@company.com", type: "string" }, phone: { value: "+1-555-0120", type: "string" }, address: { value: "913 Cypress Ave", type: "string" }, city: { value: "Boston", type: "string" }, role: { value: "Designer", type: "string" }, createdat: { value: "2024-05-20", type: "string" }, updatedat: { value: "2024-10-02", type: "string" } },
        { username: { value: "Charles Walker", type: "string" }, email: { value: "c.walker@company.com", type: "string" }, phone: { value: "+1-555-0121", type: "string" }, address: { value: "124 Laurel Rd", type: "string" }, city: { value: "El Paso", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-06-01", type: "string" }, updatedat: { value: "2024-09-30", type: "string" } },
        { username: { value: "Susan Young", type: "string" }, email: { value: "s.young@company.com", type: "string" }, phone: { value: "+1-555-0122", type: "string" }, address: { value: "235 Juniper St", type: "string" }, city: { value: "Nashville", type: "string" }, role: { value: "Analyst", type: "string" }, createdat: { value: "2024-06-05", type: "string" }, updatedat: { value: "2024-10-03", type: "string" } },
        { username: { value: "Paul Allen", type: "string" }, email: { value: "p.allen@company.com", type: "string" }, phone: { value: "+1-555-0123", type: "string" }, address: { value: "346 Fir Dr", type: "string" }, city: { value: "Detroit", type: "string" }, role: { value: "Manager", type: "string" }, createdat: { value: "2024-06-10", type: "string" }, updatedat: { value: "2024-09-28", type: "string" } },
        { username: { value: "Jessica King", type: "string" }, email: { value: "j.king@company.com", type: "string" }, phone: { value: "+1-555-0124", type: "string" }, address: { value: "457 Palm Ln", type: "string" }, city: { value: "Memphis", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-06-15", type: "string" }, updatedat: { value: "2024-10-01", type: "string" } },
        { username: { value: "Mark Wright", type: "string" }, email: { value: "m.wright@company.com", type: "string" }, phone: { value: "+1-555-0125", type: "string" }, address: { value: "568 Eucalyptus Ave", type: "string" }, city: { value: "Portland", type: "string" }, role: { value: "Designer", type: "string" }, createdat: { value: "2024-06-20", type: "string" }, updatedat: { value: "2024-09-29", type: "string" } },
        { username: { value: "Karen Scott", type: "string" }, email: { value: "k.scott@company.com", type: "string" }, phone: { value: "+1-555-0126", type: "string" }, address: { value: "679 Sequoia Rd", type: "string" }, city: { value: "Oklahoma City", type: "string" }, role: { value: "Admin", type: "string" }, createdat: { value: "2024-07-01", type: "string" }, updatedat: { value: "2024-10-04", type: "string" } },
        { username: { value: "Steven Green", type: "string" }, email: { value: "s.green@company.com", type: "string" }, phone: { value: "+1-555-0127", type: "string" }, address: { value: "780 Acacia St", type: "string" }, city: { value: "Las Vegas", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-07-05", type: "string" }, updatedat: { value: "2024-09-27", type: "string" } },
        { username: { value: "Betty Adams", type: "string" }, email: { value: "b.adams@company.com", type: "string" }, phone: { value: "+1-555-0128", type: "string" }, address: { value: "891 Mahogany Dr", type: "string" }, city: { value: "Louisville", type: "string" }, role: { value: "Analyst", type: "string" }, createdat: { value: "2024-07-10", type: "string" }, updatedat: { value: "2024-10-02", type: "string" } },
        { username: { value: "Edward Baker", type: "string" }, email: { value: "e.baker@company.com", type: "string" }, phone: { value: "+1-555-0129", type: "string" }, address: { value: "902 Teak Ln", type: "string" }, city: { value: "Baltimore", type: "string" }, role: { value: "Manager", type: "string" }, createdat: { value: "2024-07-15", type: "string" }, updatedat: { value: "2024-09-30", type: "string" } },
        { username: { value: "Dorothy Nelson", type: "string" }, email: { value: "d.nelson@company.com", type: "string" }, phone: { value: "+1-555-0130", type: "string" }, address: { value: "113 Rosewood Ave", type: "string" }, city: { value: "Milwaukee", type: "string" }, role: { value: "Designer", type: "string" }, createdat: { value: "2024-07-20", type: "string" }, updatedat: { value: "2024-10-03", type: "string" } },
        { username: { value: "Brian Carter", type: "string" }, email: { value: "b.carter@company.com", type: "string" }, phone: { value: "+1-555-0131", type: "string" }, address: { value: "224 Bamboo Rd", type: "string" }, city: { value: "Albuquerque", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-08-01", type: "string" }, updatedat: { value: "2024-09-28", type: "string" } },
        { username: { value: "Sandra Mitchell", type: "string" }, email: { value: "s.mitchell@company.com", type: "string" }, phone: { value: "+1-555-0132", type: "string" }, address: { value: "335 Ironwood St", type: "string" }, city: { value: "Tucson", type: "string" }, role: { value: "Analyst", type: "string" }, createdat: { value: "2024-08-05", type: "string" }, updatedat: { value: "2024-10-01", type: "string" } },
        { username: { value: "Ronald Perez", type: "string" }, email: { value: "r.perez@company.com", type: "string" }, phone: { value: "+1-555-0133", type: "string" }, address: { value: "446 Cottonwood Dr", type: "string" }, city: { value: "Fresno", type: "string" }, role: { value: "Manager", type: "string" }, createdat: { value: "2024-08-10", type: "string" }, updatedat: { value: "2024-09-29", type: "string" } },
        { username: { value: "Ashley Roberts", type: "string" }, email: { value: "a.roberts@company.com", type: "string" }, phone: { value: "+1-555-0134", type: "string" }, address: { value: "557 Chestnut Ln", type: "string" }, city: { value: "Sacramento", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-08-15", type: "string" }, updatedat: { value: "2024-10-04", type: "string" } },
        { username: { value: "Kevin Turner", type: "string" }, email: { value: "k.turner@company.com", type: "string" }, phone: { value: "+1-555-0135", type: "string" }, address: { value: "668 Basswood Ave", type: "string" }, city: { value: "Kansas City", type: "string" }, role: { value: "Designer", type: "string" }, createdat: { value: "2024-08-20", type: "string" }, updatedat: { value: "2024-09-27", type: "string" } },
        { username: { value: "Donna Phillips", type: "string" }, email: { value: "d.phillips@company.com", type: "string" }, phone: { value: "+1-555-0136", type: "string" }, address: { value: "779 Ebony Rd", type: "string" }, city: { value: "Mesa", type: "string" }, role: { value: "Admin", type: "string" }, createdat: { value: "2024-09-01", type: "string" }, updatedat: { value: "2024-10-02", type: "string" } },
        { username: { value: "Jason Campbell", type: "string" }, email: { value: "j.campbell@company.com", type: "string" }, phone: { value: "+1-555-0137", type: "string" }, address: { value: "880 Pecan St", type: "string" }, city: { value: "Virginia Beach", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-09-05", type: "string" }, updatedat: { value: "2024-09-30", type: "string" } },
        { username: { value: "Michelle Parker", type: "string" }, email: { value: "m.parker@company.com", type: "string" }, phone: { value: "+1-555-0138", type: "string" }, address: { value: "991 Olive Dr", type: "string" }, city: { value: "Atlanta", type: "string" }, role: { value: "Analyst", type: "string" }, createdat: { value: "2024-09-10", type: "string" }, updatedat: { value: "2024-10-03", type: "string" } },
        { username: { value: "Gary Evans", type: "string" }, email: { value: "g.evans@company.com", type: "string" }, phone: { value: "+1-555-0139", type: "string" }, address: { value: "102 Linden Ln", type: "string" }, city: { value: "Colorado Springs", type: "string" }, role: { value: "Manager", type: "string" }, createdat: { value: "2024-09-15", type: "string" }, updatedat: { value: "2024-09-28", type: "string" } },
        { username: { value: "Carol Edwards", type: "string" }, email: { value: "c.edwards@company.com", type: "string" }, phone: { value: "+1-555-0140", type: "string" }, address: { value: "213 Sandalwood Ave", type: "string" }, city: { value: "Raleigh", type: "string" }, role: { value: "Designer", type: "string" }, createdat: { value: "2024-09-20", type: "string" }, updatedat: { value: "2024-10-01", type: "string" } },
        { username: { value: "Larry Collins", type: "string" }, email: { value: "l.collins@company.com", type: "string" }, phone: { value: "+1-555-0141", type: "string" }, address: { value: "324 Mesquite Rd", type: "string" }, city: { value: "Omaha", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-09-25", type: "string" }, updatedat: { value: "2024-09-29", type: "string" } },
        { username: { value: "Sharon Stewart", type: "string" }, email: { value: "s.stewart@company.com", type: "string" }, phone: { value: "+1-555-0142", type: "string" }, address: { value: "435 Alder St", type: "string" }, city: { value: "Miami", type: "string" }, role: { value: "Analyst", type: "string" }, createdat: { value: "2024-09-28", type: "string" }, updatedat: { value: "2024-10-04", type: "string" } },
        { username: { value: "Jeffrey Sanchez", type: "string" }, email: { value: "j.sanchez@company.com", type: "string" }, phone: { value: "+1-555-0143", type: "string" }, address: { value: "546 Hawthorn Dr", type: "string" }, city: { value: "Oakland", type: "string" }, role: { value: "Manager", type: "string" }, createdat: { value: "2024-10-01", type: "string" }, updatedat: { value: "2024-10-02", type: "string" } },
        { username: { value: "Cynthia Morris", type: "string" }, email: { value: "c.morris@company.com", type: "string" }, phone: { value: "+1-555-0144", type: "string" }, address: { value: "657 Boxwood Ln", type: "string" }, city: { value: "Minneapolis", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-10-02", type: "string" }, updatedat: { value: "2024-10-03", type: "string" } },
        { username: { value: "Frank Rogers", type: "string" }, email: { value: "f.rogers@company.com", type: "string" }, phone: { value: "+1-555-0145", type: "string" }, address: { value: "768 Buckeye Ave", type: "string" }, city: { value: "Tulsa", type: "string" }, role: { value: "Designer", type: "string" }, createdat: { value: "2024-10-03", type: "string" }, updatedat: { value: "2024-10-04", type: "string" } },
        { username: { value: "Angela Reed", type: "string" }, email: { value: "a.reed@company.com", type: "string" }, phone: { value: "+1-555-0146", type: "string" }, address: { value: "879 Buttonwood Rd", type: "string" }, city: { value: "Cleveland", type: "string" }, role: { value: "Admin", type: "string" }, createdat: { value: "2024-10-04", type: "string" }, updatedat: { value: "2024-10-04", type: "string" } },
        { username: { value: "Scott Cook", type: "string" }, email: { value: "s.cook@company.com", type: "string" }, phone: { value: "+1-555-0147", type: "string" }, address: { value: "980 Sassafras St", type: "string" }, city: { value: "Wichita", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-10-05", type: "string" }, updatedat: { value: "2024-10-05", type: "string" } },
        { username: { value: "Deborah Morgan", type: "string" }, email: { value: "d.morgan@company.com", type: "string" }, phone: { value: "+1-555-0148", type: "string" }, address: { value: "091 Blackwood Dr", type: "string" }, city: { value: "Arlington", type: "string" }, role: { value: "Analyst", type: "string" }, createdat: { value: "2024-10-06", type: "string" }, updatedat: { value: "2024-10-06", type: "string" } },
        { username: { value: "Raymond Bell", type: "string" }, email: { value: "r.bell@company.com", type: "string" }, phone: { value: "+1-555-0149", type: "string" }, address: { value: "192 Maplewood Ln", type: "string" }, city: { value: "New Orleans", type: "string" }, role: { value: "Manager", type: "string" }, createdat: { value: "2024-10-07", type: "string" }, updatedat: { value: "2024-10-07", type: "string" } },
        { username: { value: "Helen Murphy", type: "string" }, email: { value: "h.murphy@company.com", type: "string" }, phone: { value: "+1-555-0150", type: "string" }, address: { value: "203 Oakmont Ave", type: "string" }, city: { value: "Bakersfield", type: "string" }, role: { value: "Developer", type: "string" }, createdat: { value: "2024-10-08", type: "string" }, updatedat: { value: "2024-10-08", type: "string" } }
    ]  ,
    pageIndex : 0,
    totalItems : 50,
    totalPages : 25,  // 50 items / 2 items per page = 25 pages
    totalItemsPerPage : 2,
    download : true,
};  

export default usersData;