//  COLUMN_TYPES_SUPPORTED : [
//     'string', 'number', 'date', 'boolean', 'object' , 'datetime',
// ]

export const projectsTableMeta = {
  tableId: "projects",
  viewId: "default",
  views: [
    { id: "default", name: "All Projects" },
    { id: "active", name: "Active Projects" },
    { id: "my_projects", name: "My Projects" },
  ],
  download: {
    enabled: true,
    formats: ["csv", "excel"],
  },
};

export const projectsTableConfig = [
  {
    id: 1,
    order: 1,
    fieldName: "projectName",
    displayName: "Project Name",
    dbFieldName: "project_name",
    sort: true,
    search: true,
    filter: false,
    type: "string",
    link: true,
  },
  {
    id: 2,
    order: 2,
    fieldName: "description",
    displayName: "Description",
    dbFieldName: "description",
    sort: false,
    search: true,
    filter: false,
    type: "string",
  },
  {
    id: 3,
    order: 3,
    fieldName: "ownerName",
    displayName: "Project Owner",
    dbFieldName: "owner_name",
    sort: true,
    search: true,
    filter: false,
    type: "string",
  },
  {
    id: 4,
    order: 4,
    fieldName: "status",
    displayName: "Status",
    dbFieldName: "status",
    sort: true,
    search: false,
    filter: true,
    type: "string",
    badgeMap: {
      ACTIVE: { text: "Active", color: "green" },
      INACTIVE: { text: "Inactive", color: "gray" },
      COMPLETED: { text: "Completed", color: "gray" },
      ON_HOLD: { text: "On Hold", color: "orange" },
    },
  },
  {
    id: 5,
    order: 5,
    fieldName: "priority",
    displayName: "Priority",
    dbFieldName: "priority",
    sort: true,
    search: false,
    filter: true,
    type: "string",
    badgeMap: {
      LOW: { text: "Low", color: "gray" },
      MEDIUM: { text: "Medium", color: "orange" },
      HIGH: { text: "High", color: "red" },
      URGENT: { text: "Urgent", color: "purple" },
    },
  },
  {
    id: 6,
    order: 6,
    fieldName: "startDate",
    displayName: "Start Date",
    dbFieldName: "start_date",
    sort: true,
    search: false,
    filter: false,
    type: "date",
    format: "DD-MM-YYYY",
  },
  {
    id: 7,
    order: 7,
    fieldName: "endDate",
    displayName: "End Date",
    dbFieldName: "end_date",
    sort: true,
    search: false,
    filter: false,
    type: "date",
    format: "DD-MM-YYYY",
  },
  {
    id: 8,
    order: 8,
    fieldName: "createdAt",
    displayName: "Created At",
    dbFieldName: "created_at",
    sort: true,
    search: false,
    filter: false,
    type: "datetime",
    format: "DD-MM-YYYY H:MM:SS",
  },
];
